version: '3'

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: potato-plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #
    volumes:
      - ./packages/plex/config:/config
      - /storage/Series:/tv
      - /storage/Movies:/movies
    ports:
      - 32400:32400
      - 1900:1900
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32469:32469
    restart: unless-stopped

